const ACTION_TYPES = {
  FETCH_ALL_POSTS: "FETCH_ALL_POSTS",
  CREATE_POST: "CREATE_POST",
  UPDATE_POST: "UPDATE_POST",
  DELETE_POST: "DELETE_POST",
  LIKE_POST: "LIKE_POST",
};

export default ACTION_TYPES;
